CREATE TABLE submissions (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     business_key VARCHAR(60) UNIQUE NOT NULL,
     user_id VARCHAR(64) NOT NULL,
     url VARCHAR(255) NOT NULL,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analysis_results (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      submission_key VARCHAR(60) UNIQUE NOT NULL,
      maintainability_score INT NOT NULL,
      complexity_score INT NOT NULL,
      duplication_score INT NOT NULL,
      solid_violations INT NOT NULL
);

CREATE TABLE points_ledger (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       user_id VARCHAR(64) NOT NULL,
       submission_key VARCHAR(60) UNIQUE NOT NULL,
       points INT NOT NULL,
       awarded_at TIMESTAMP NOT NULL
);

CREATE TABLE leaderboard (
     user_id VARCHAR(64) PRIMARY KEY,
     total_points INT NOT NULL
);
